### ISSUE TITLE
Installing in virtual environment

### ISSUE THREAD

**Issue by bzablocki** [dillonalaird/shared_numpy#1]
Hi! I wanted to install your module in my virtual environment (Python3.6), but it doesn't seem to work. 

When I build it using the method provided ```python setup.py build_ext --inplace```, the module is visible only when I run python from the shared_numpy directory. It's not visible in my virtual environment. 

When I tried to install it with ```python setup.py install``` and later also with 'pip install .', the module was visible in the virtual environment (no error on 'import shared_numpy as snp'), but attributes of the module were not visible.

```
>>> import shared_numpy as snp
>>> snp.Queue
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'shared_numpy' has no attribute 'Queue'
```

I don't have any experience with creating and installing modules like this, could you help me solve the issue?

**Comment by bzablocki** [comment]
Alright, I figured it out. Only later I realized that the directory 'shared_numpy' is not built and shared globally. So the line ```import shared_numpy as snp``` is actually referring to the directory, not to the installed module. Copying that directory to a project that I'm working on solved the issue. :+1:

**Comment by joinvar** [comment]
When I follow your step and i run the examples ,but i  got a error.
![image](https://user-images.githubusercontent.com/26863094/167299553-71ae15bd-6e01-44bb-a05e-7bf39321697b.png)
Have you ever encountered this?

**Comment by joinvar** [comment]
Does it not support windows?
