### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by rafalcieslak** [dillonalaird/shared_numpy#2]
Hi. This library looks very useful.

I am hoping to use this library in another project, but at the moment it is unclear if I am allowed to do that.

If you are okay with others using this library, could you please update the project with licensing information? Ideally that would include a `LICENSE` file describing your terms, or a copy of a license you are happy with.

On the other hand, if you do not wish others reuse your work, I'll respect that.

**Comment by eedalong** [comment]
+1 @dillonalaird

**Comment by eedalong** [comment]
License Needed ~

**Comment by dillonalaird** [comment]
Feel free to use the code! I just added an MIT license, thanks for the suggestion
